# Generated by Django 4.2.8 on 2026-02-08 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='名字', max_length=50)),
                ('role', models.CharField(help_text='角色', max_length=50)),
                ('tier', models.CharField(choices=[('FULL', '完整Agent (LLM驱动)'), ('LIGHT', '轻量Agent (规则+模板)')], help_text='层级', max_length=5)),
                ('attributes', models.JSONField(default=dict, help_text='所有属性 (JSONB)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'agents',
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affinity', models.IntegerField(default=10, help_text='好感度 (-99 to 99)')),
                ('data', models.JSONField(default=dict, help_text='其他关系数据')),
                ('agent_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_a', to='game.agent')),
                ('agent_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_b', to='game.agent')),
            ],
            options={
                'db_table': 'relationships',
            },
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_season', models.IntegerField(default=1, help_text='当前季度 (1-12)')),
                ('county_data', models.JSONField(default=dict, help_text='所有县域数据')),
                ('pending_events', models.JSONField(default=list, help_text='待处理事件')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'game_states',
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(help_text='触发季度')),
                ('event_type', models.CharField(help_text='事件类型', max_length=100)),
                ('choice', models.CharField(blank=True, default='', help_text='玩家选择', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='game.gamestate')),
            ],
            options={
                'db_table': 'event_logs',
            },
        ),
        migrations.AddConstraint(
            model_name='relationship',
            constraint=models.UniqueConstraint(fields=('agent_a', 'agent_b'), name='unique_relationship'),
        ),
        migrations.AddIndex(
            model_name='gamestate',
            index=models.Index(fields=['user', '-updated_at'], name='game_states_user_id_187e9f_idx'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['game', 'season'], name='event_logs_game_id_afc6b6_idx'),
        ),
    ]
