# Generated by Django 4.2.8 on 2026-02-09 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.CharField(choices=[('HUMBLE', '寒门子弟'), ('SCHOLAR', '书香门第'), ('OFFICIAL', '官宦之后')], help_text='出身背景', max_length=10)),
                ('knowledge', models.FloatField(default=3.0, help_text='知识：农耕/经济/地理，影响治理效果')),
                ('skill', models.FloatField(default=3.0, help_text='技能：谈判/协调，影响谈判效果')),
                ('integrity', models.IntegerField(default=50, help_text='清名：公正廉洁的口碑')),
                ('competence', models.IntegerField(default=30, help_text='能名：干练能干的口碑')),
                ('popularity', models.IntegerField(default=10, help_text='人缘：官场好相处的口碑')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='game.gamestate')),
            ],
            options={
                'db_table': 'player_profiles',
            },
        ),
    ]
