# Generated by Django 4.2.8 on 2026-02-10 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_agent_dialogue'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agent',
            new_name='agents_game_id_d87afe_idx',
            old_name='agents_game_id_e71a47_idx',
        ),
        migrations.RenameIndex(
            model_name='dialoguemessage',
            new_name='dialogue_me_game_id_3dcd0e_idx',
            old_name='dialogue_me_game_id_1a2b3c_idx',
        ),
    ]
