# Generated by Django 4.2.8 on 2026-02-11 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_rename_agents_game_id_e71a47_idx_agents_game_id_d87afe_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NegotiationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ANNEXATION', '地主兼并'), ('IRRIGATION', '兴建水利')], max_length=20)),
                ('status', models.CharField(choices=[('active', '进行中'), ('resolved', '已结算')], default='active', max_length=10)),
                ('current_round', models.IntegerField(default=0)),
                ('max_rounds', models.IntegerField(help_text='ANNEXATION=8, IRRIGATION=12')),
                ('season', models.IntegerField(help_text='触发时的季度')),
                ('context_data', models.JSONField(default=dict, help_text='事件参数')),
                ('outcome', models.JSONField(blank=True, default=dict, help_text='结算结果')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='game.agent')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='game.gamestate')),
            ],
            options={
                'db_table': 'negotiation_sessions',
                'indexes': [models.Index(fields=['game', 'status'], name='negotiation_game_id_039344_idx'), models.Index(fields=['game', 'event_type', '-created_at'], name='negotiation_game_id_8628f4_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='negotiationsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('game',), name='one_active_negotiation_per_game'),
        ),
    ]
