# Generated by Django 4.2.8 on 2026-02-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_negotiation_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='category',
            field=models.CharField(choices=[('SYSTEM', '系统'), ('INVESTMENT', '投资'), ('TAX', '税率'), ('NEGOTIATION', '谈判'), ('DISASTER', '灾害'), ('SETTLEMENT', '结算'), ('ANNEXATION', '兼并')], default='SYSTEM', help_text='事件分类', max_length=20),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='data',
            field=models.JSONField(blank=True, default=dict, help_text='结构化事件数据'),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='description',
            field=models.TextField(blank=True, default='', help_text='人类可读的事件描述'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['game', 'category'], name='event_logs_game_id_d742f8_idx'),
        ),
    ]
