# Generated by Django 4.2.8 on 2026-02-20 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_promise'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeighborCounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_name', models.CharField(help_text='邻县名称', max_length=100)),
                ('governor_name', models.CharField(help_text='AI知县姓名', max_length=50)),
                ('governor_style', models.CharField(choices=[('minben', '民本型'), ('zhengji', '政绩型'), ('baoshou', '保守型'), ('jinqu', '进取型'), ('yuanhua', '圆滑型')], help_text='施政风格', max_length=20)),
                ('governor_bio', models.TextField(blank=True, default='', help_text='知县人设描述')),
                ('county_data', models.JSONField(default=dict, help_text='同玩家county_data结构')),
                ('last_reasoning', models.TextField(blank=True, default='', help_text='上季度LLM决策reasoning')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'neighbor_counties',
            },
        ),
        migrations.CreateModel(
            name='NeighborEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(help_text='触发季度')),
                ('event_type', models.CharField(help_text='事件类型', max_length=100)),
                ('category', models.CharField(choices=[('SETTLEMENT', '结算'), ('DISASTER', '灾害'), ('INVESTMENT', '投资'), ('TAX', '税率'), ('AI_DECISION', 'AI决策')], default='SETTLEMENT', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'neighbor_event_logs',
            },
        ),
        migrations.RenameIndex(
            model_name='promise',
            new_name='promises_game_id_dd0a24_idx',
            old_name='promises_game_id_status_idx',
        ),
        migrations.RenameIndex(
            model_name='promise',
            new_name='promises_game_id_c965b2_idx',
            old_name='promises_game_id_agent_idx',
        ),
        migrations.AlterField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('ADVISOR', '师爷'), ('DEPUTY', '县丞'), ('PREFECT', '知府'), ('GENTRY', '士绅'), ('VILLAGER', '村民')], help_text='角色', max_length=50),
        ),
        migrations.AddField(
            model_name='neighboreventlog',
            name='neighbor_county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='game.neighborcounty'),
        ),
        migrations.AddField(
            model_name='neighborcounty',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighbors', to='game.gamestate'),
        ),
        migrations.AddIndex(
            model_name='neighboreventlog',
            index=models.Index(fields=['neighbor_county', 'season'], name='neighbor_ev_neighbo_a38648_idx'),
        ),
        migrations.AddIndex(
            model_name='neighborcounty',
            index=models.Index(fields=['game'], name='neighbor_co_game_id_57ab3e_idx'),
        ),
    ]
