# Generated by Django 4.2.8 on 2026-02-26 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0008_neighborcounty_neighboreventlog_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="negotiationsession",
            name="one_active_negotiation_per_game",
        ),
    ]
