# Generated by Django 4.2.8 on 2026-02-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_remove_one_active_negotiation_per_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialoguemessage',
            name='season',
            field=models.IntegerField(help_text='对话时的月份'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='season',
            field=models.IntegerField(help_text='触发月份'),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='current_season',
            field=models.IntegerField(default=1, help_text='当前月份 (1-36)'),
        ),
        migrations.AlterField(
            model_name='negotiationsession',
            name='event_type',
            field=models.CharField(choices=[('ANNEXATION', '地主兼并'), ('IRRIGATION', '兴建水利'), ('HIDDEN_LAND', '隐匿土地')], max_length=20),
        ),
        migrations.AlterField(
            model_name='negotiationsession',
            name='season',
            field=models.IntegerField(help_text='触发时的月份'),
        ),
        migrations.AlterField(
            model_name='neighborcounty',
            name='last_reasoning',
            field=models.TextField(blank=True, default='', help_text='上月LLM决策reasoning'),
        ),
        migrations.AlterField(
            model_name='neighboreventlog',
            name='season',
            field=models.IntegerField(help_text='触发月份'),
        ),
        migrations.AlterField(
            model_name='promise',
            name='deadline_season',
            field=models.IntegerField(help_text='履约截止月份'),
        ),
        migrations.AlterField(
            model_name='promise',
            name='season_made',
            field=models.IntegerField(help_text='承诺时的月份'),
        ),
        migrations.AddConstraint(
            model_name='negotiationsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('game', 'agent'), name='one_active_negotiation_per_agent'),
        ),
    ]
