# Generated by Django 4.2.8 on 2026-02-27 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_add_negotiation_agent_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeighborPrecompute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(help_text='预计算对应的月份')),
                ('results', models.JSONField(default=dict, help_text='各邻县AI决策结果')),
                ('status', models.CharField(choices=[('computing', '计算中'), ('done', '已完成')], default='computing', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='neighbor_precompute', to='game.gamestate')),
            ],
            options={
                'db_table': 'neighbor_precomputes',
            },
        ),
    ]
