# Generated by Django 4.2.8 on 2026-03-02 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_neighborprecompute'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='source_name',
            field=models.CharField(blank=True, default='', help_text='历史原型真名（如 徐阶）', max_length=50),
        ),
        migrations.AlterField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('ADVISOR', '师爷'), ('DEPUTY', '县丞'), ('PREFECT', '知府'), ('GENTRY', '士绅'), ('VILLAGER', '村民'), ('EMPEROR', '皇帝'), ('CABINET_CHIEF', '内阁首辅'), ('CABINET_MEMBER', '内阁成员'), ('MINISTER', '尚书'), ('VICE_MINISTER', '侍郎'), ('CENSOR', '御史'), ('GOVERNOR_GENERAL', '总督'), ('PROVINCIAL_GOVERNOR', '巡抚'), ('PROVINCIAL_COMMISSIONER', '布政使/按察使')], help_text='角色', max_length=50),
        ),
        migrations.CreateModel(
            name='MonarchProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archetype', models.CharField(choices=[('diligent', '勤政型'), ('delegating', '怠政型'), ('moderate', '中庸型')], help_text='君主原型', max_length=20)),
                ('attributes', models.JSONField(default=dict, help_text='治国系数 (tax_pressure, corruption_risk等)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.OneToOneField(blank=True, help_text='关联的皇帝Agent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monarch_profile', to='game.agent')),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monarch', to='game.gamestate')),
            ],
            options={
                'db_table': 'monarch_profiles',
            },
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='派系名称', max_length=50)),
                ('ideology', models.JSONField(default=dict, help_text='派系意识形态 (state_vs_people等)')),
                ('imperial_favor', models.IntegerField(default=50, help_text='圣眷 (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factions', to='game.gamestate')),
                ('leader', models.ForeignKey(blank=True, help_text='派系领袖', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_factions', to='game.agent')),
            ],
            options={
                'db_table': 'factions',
                'indexes': [models.Index(fields=['game'], name='factions_game_id_03bc6f_idx')],
            },
        ),
    ]
