# Generated by Django 4.2.8 on 2026-03-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_officialdom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('ADVISOR', '师爷'), ('DEPUTY', '县丞'), ('PREFECT', '知府'), ('GENTRY', '士绅'), ('VILLAGER', '村民'), ('EMPEROR', '皇帝'), ('CABINET_CHIEF', '内阁首辅'), ('CABINET_MEMBER', '内阁成员'), ('MINISTER', '尚书'), ('VICE_MINISTER', '侍郎'), ('CHIEF_CENSOR', '左都御史'), ('VICE_CENSOR', '左副都御史'), ('CENSOR', '监察御史'), ('GOVERNOR_GENERAL', '总督'), ('PROVINCIAL_GOVERNOR', '巡抚'), ('PROVINCIAL_COMMISSIONER', '布政使/按察使'), ('PREFECT_PEER', '知州')], help_text='角色', max_length=50),
        ),
    ]
