# Generated by Django 4.2.8 on 2026-03-19 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_player_profile_v2'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adminunit',
            new_name='admin_units_game_id_1c819a_idx',
            old_name='admin_units_game_unit_idx',
        ),
        migrations.RenameIndex(
            model_name='adminunit',
            new_name='admin_units_parent__4338a1_idx',
            old_name='admin_units_parent_idx',
        ),
        migrations.RenameIndex(
            model_name='judicialcaseinstance',
            new_name='judicial_ca_game_id_9e4392_idx',
            old_name='judicial_ca_game_id_566bd8_idx',
        ),
        migrations.RenameIndex(
            model_name='judicialcaseinstance',
            new_name='judicial_ca_game_id_850081_idx',
            old_name='judicial_ca_game_id_a1f2ca_idx',
        ),
        migrations.RenameIndex(
            model_name='judicialcaseinstance',
            new_name='judicial_ca_county__d594a5_idx',
            old_name='judicial_ca_county__5ca58c_idx',
        ),
        migrations.RenameIndex(
            model_name='judicialcaseinstance',
            new_name='judicial_ca_prefect_dd6134_idx',
            old_name='judicial_ca_prefect_8a4a9b_idx',
        ),
        migrations.AddField(
            model_name='neighborcounty',
            name='attributes',
            field=models.JSONField(default=dict, help_text='AI知县属性：player_affinity(对玩家好感度, 0-99), memory(记忆列表, 最近20条)'),
        ),
        migrations.AlterField(
            model_name='adminunit',
            name='ai_agent',
            field=models.ForeignKey(blank=True, help_text='AI治理官员（非玩家控制时）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governed_units', to='game.agent'),
        ),
        migrations.AlterField(
            model_name='adminunit',
            name='unit_data',
            field=models.JSONField(default=dict, help_text='行政单元状态数据（与county_data同结构或府/省专用结构）'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='category',
            field=models.CharField(choices=[('SYSTEM', '系统'), ('INVESTMENT', '投资'), ('TAX', '税率'), ('NEGOTIATION', '谈判'), ('DISASTER', '灾害'), ('SETTLEMENT', '结算'), ('ANNEXATION', '兼并'), ('PROMISE', '承诺'), ('PREFECT', '知府')], default='SYSTEM', help_text='事件分类', max_length=20),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='county_data',
            field=models.JSONField(default=dict, help_text='所有县域数据（知县游戏用）'),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='player_role',
            field=models.CharField(choices=[('COUNTY_MAGISTRATE', '知县'), ('PREFECT', '知府'), ('GOVERNOR', '巡抚'), ('CABINET', '内阁')], default='COUNTY_MAGISTRATE', help_text='玩家当前官职层级', max_length=20),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='player_unit',
            field=models.ForeignKey(blank=True, help_text='玩家当前治理的行政单元', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_game', to='game.adminunit'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='authority',
            field=models.IntegerField(default=40, help_text='威名：必要时强硬、令人敬畏的口碑'),
        ),
    ]
