# Generated by Django 4.2.8 on 2026-03-20 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0020_playerfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='客户端 IP', null=True)),
                ('user_agent', models.CharField(blank=True, default='', help_text='浏览器 User-Agent', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_login_logs',
            },
        ),
        migrations.RenameIndex(
            model_name='playerfeedback',
            new_name='player_feed_user_id_81aff9_idx',
            old_name='player_feed_user_id_03431d_idx',
        ),
        migrations.RenameIndex(
            model_name='playerfeedback',
            new_name='player_feed_game_id_3393a7_idx',
            old_name='player_feed_game_id_85331e_idx',
        ),
        migrations.AddField(
            model_name='userloginlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userloginlog',
            index=models.Index(fields=['user', '-created_at'], name='user_login__user_id_5ccc0c_idx'),
        ),
    ]
