# Generated by Django 4.2.8 on 2026-03-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_user_login_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginlog',
            name='logged_out_at',
            field=models.DateTimeField(blank=True, help_text='登出时间（null = session 仍开着或异常断开）', null=True),
        ),
    ]
