# Generated by Django 4.2.8 on 2026-03-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_user_login_log_logout'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginlog',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, help_text='Django session key，用于精确匹配登出记录', max_length=40, null=True),
        ),
    ]
