# Generated by Django 4.2.8 on 2026-03-25 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_letter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposedPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposer', models.CharField(help_text='提案人：知县 / 师爷 / 县丞', max_length=50)),
                ('raw_proposal', models.TextField(help_text='原始申请描述（玩家/NPC 的自然语言表述）')),
                ('policy_name', models.CharField(help_text='施政选项名称', max_length=100)),
                ('action_key', models.CharField(blank=True, help_text='布政使批准后生成的唯一动作标识，供 InvestmentService 识别', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', '待审核'), ('APPROVED', '已批准'), ('REJECTED', '已拒绝'), ('ARCHIVED', '管理员归档（不采纳）'), ('PROMOTED', '已提升为标准选项')], db_index=True, default='PENDING', max_length=20)),
                ('cost', models.IntegerField(blank=True, help_text='批准花费（两），批复后填入', null=True)),
                ('delay_months', models.IntegerField(blank=True, help_text='工期（月），批复后填入', null=True)),
                ('effects_data', models.JSONField(default=dict, help_text='效果定义，格式：{"immediate": {"morale": 3}, "on_complete": {"commercial": 15}, "add_market": {"merchants": 10}, "description": "..."}')),
                ('rationale', models.TextField(blank=True, help_text='布政使批复原文（批准或拒绝均填写）')),
                ('rejection_reason', models.TextField(blank=True, help_text='拒绝原因（REJECTED 时填写）')),
                ('is_executed', models.BooleanField(default=False, help_text='本县是否已执行过此选项')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='布政使批复时间', null=True)),
                ('rejected_at', models.DateTimeField(blank=True, help_text='拒绝时间，用于6个月冷却计算', null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_policies', to='game.gamestate')),
                ('synced_from', models.ForeignKey(blank=True, help_text='邻县同步时指向原始申请记录，本县原始申请此字段为 null', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synced_copies', to='game.proposedpolicy')),
            ],
            options={
                'db_table': 'proposed_policies',
            },
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='category',
            field=models.CharField(choices=[('SYSTEM', '系统'), ('INVESTMENT', '投资'), ('TAX', '税率'), ('NEGOTIATION', '谈判'), ('JUDICIAL', '司法'), ('LETTER', '书信'), ('BRIBERY', '行贿'), ('PROFILE', '声望'), ('DISASTER', '灾害'), ('SETTLEMENT', '结算'), ('ANNEXATION', '兼并'), ('PROMISE', '承诺'), ('PREFECT', '知府')], default='SYSTEM', help_text='事件分类', max_length=20),
        ),
        migrations.AlterField(
            model_name='letter',
            name='circular_recipient_ids',
            field=models.JSONField(blank=True, default=list, help_text='檄文专用：多收件NPC的Agent ID列表'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='default_choice_id',
            field=models.CharField(blank=True, help_text='软deadline超时自动选项', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='delivered_month',
            field=models.IntegerField(help_text='sent_month + delivery_delay'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='delivery_delay',
            field=models.IntegerField(default=1, help_text='送达延迟（月）'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='is_blocking',
            field=models.BooleanField(default=False, help_text='True=超时未回复则硬阻断月份推进'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='reply_options',
            field=models.JSONField(blank=True, help_text='None=自由回复; list=选择题选项', null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='sent_month',
            field=models.IntegerField(help_text='发出时的游戏绝对月份'),
        ),
        migrations.CreateModel(
            name='StandardPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_key', models.CharField(help_text='唯一动作标识，不可与内置 INVESTMENT_TYPES 键名重复', max_length=100, unique=True)),
                ('policy_name', models.CharField(help_text='施政选项名称（投资面板展示用）', max_length=100)),
                ('cost_base', models.IntegerField(help_text='基准花费（两），实际花费 = cost_base × price_index')),
                ('delay_months', models.IntegerField(help_text='工期（月）；0 表示即时生效')),
                ('requires_village', models.BooleanField(default=False, help_text='是否需要指定目标村庄')),
                ('effects_data', models.JSONField(default=dict, help_text='效果定义，格式同 ProposedPolicy.effects_data')),
                ('description', models.TextField(blank=True, help_text='施政选项简述，显示在投资面板')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False 时不出现在新对局中（管理员可临时停用）')),
                ('promoted_at', models.DateTimeField(auto_now_add=True, help_text='提升时间')),
                ('promoted_by', models.CharField(help_text='操作管理员用户名', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='管理员备注（平衡性说明等）')),
                ('source_policy', models.ForeignKey(blank=True, help_text='来源 ProposedPolicy，追溯用', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standard_versions', to='game.proposedpolicy')),
            ],
            options={
                'db_table': 'standard_policies',
                'indexes': [models.Index(fields=['is_active'], name='standard_po_is_acti_2f5496_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='proposedpolicy',
            index=models.Index(fields=['game', 'status'], name='proposed_po_game_id_4e2b76_idx'),
        ),
        migrations.AddIndex(
            model_name='proposedpolicy',
            index=models.Index(fields=['game', 'policy_name'], name='proposed_po_game_id_ca00a1_idx'),
        ),
        migrations.AddIndex(
            model_name='proposedpolicy',
            index=models.Index(fields=['synced_from'], name='proposed_po_synced__7ac9c0_idx'),
        ),
    ]
