# Generated by Django 4.2.8 on 2026-03-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_add_proposed_standard_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposedpolicy',
            name='activated_game_ids',
            field=models.JSONField(default=list, help_text='Tier 2 已激活的 game_id 列表（仅对这些对局可执行）'),
        ),
        migrations.AddField(
            model_name='proposedpolicy',
            name='code_status',
            field=models.CharField(blank=True, choices=[('pending_dev', '待开发'), ('dev_complete', '开发完成'), ('activated', '已激活')], help_text='Tier 2 专用：开发状态（pending_dev/dev_complete/activated）', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='proposedpolicy',
            name='global_promotion',
            field=models.BooleanField(default=False, help_text='Tier 2 激活后：是否推广为全局可用（对所有对局生效）'),
        ),
        migrations.AddField(
            model_name='proposedpolicy',
            name='is_synced_to_neighbors',
            field=models.BooleanField(default=False, help_text='Tier 1 批准后是否已同步至邻县'),
        ),
        migrations.AddField(
            model_name='proposedpolicy',
            name='tier',
            field=models.IntegerField(default=1, help_text='施政分级：1=无需代码改动，2=需要新增后端代码'),
        ),
        migrations.AddField(
            model_name='proposedpolicy',
            name='unsupported_effects',
            field=models.JSONField(default=list, help_text='无法被现有引擎处理的 effect 键，批复时自动分析填入'),
        ),
        migrations.AddIndex(
            model_name='proposedpolicy',
            index=models.Index(fields=['tier', 'code_status'], name='proposed_po_tier_f4fd53_idx'),
        ),
    ]
