# Generated by Django 4.2.8 on 2026-03-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_proposed_policy_notification_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='category',
            field=models.CharField(choices=[('SYSTEM', '系统'), ('INVESTMENT', '投资'), ('TAX', '税率'), ('NEGOTIATION', '谈判'), ('JUDICIAL', '司法'), ('LETTER', '书信'), ('BRIBERY', '行贿'), ('PROFILE', '声望'), ('DISASTER', '灾害'), ('SETTLEMENT', '结算'), ('ANNEXATION', '兼并'), ('PROMISE', '承诺'), ('PREFECT', '知府'), ('PREFECTURE', '府政'), ('PERSONNEL', '人事')], default='SYSTEM', help_text='事件分类', max_length=20),
        ),
    ]
