# Generated by Django 4.2.8 on 2026-04-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_add_prefecture_personnel_event_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('ADVISOR', '师爷'), ('DEPUTY', '县丞'), ('PREFECT', '知府'), ('GENTRY', '士绅'), ('VILLAGER', '村民'), ('EMPEROR', '皇帝'), ('CABINET_CHIEF', '内阁首辅'), ('CABINET_MEMBER', '内阁成员'), ('MINISTER', '尚书'), ('VICE_MINISTER', '侍郎'), ('CHIEF_CENSOR', '左都御史'), ('VICE_CENSOR', '左副都御史'), ('CENSOR', '监察御史'), ('GOVERNOR_GENERAL', '总督'), ('PROVINCIAL_GOVERNOR', '巡抚'), ('PROVINCIAL_COMMISSIONER', '布政使/按察使'), ('PREFECT_PEER', '知州'), ('LIUFANG', '六房书办'), ('CONSTABLE', '捕快'), ('BAILIFF_CEREMONY', '皂班'), ('BAILIFF_LABOR', '壮班'), ('CLAN_YOUTH', '宗族后生')], help_text='角色', max_length=50),
        ),
        migrations.AlterField(
            model_name='negotiationsession',
            name='event_type',
            field=models.CharField(choices=[('ANNEXATION', '地主兼并'), ('IRRIGATION', '兴建水利'), ('HIDDEN_LAND', '隐匿土地'), ('VILLAGE_REQ_SCHOOL', '村民请愿·建村塾'), ('VILLAGE_REQ_TAX', '村民请愿·减税'), ('LANDLORD_DEMAND_FACILITY', '地主要求·升级公共设施')], max_length=30),
        ),
        migrations.AlterField(
            model_name='promise',
            name='promise_type',
            field=models.CharField(choices=[('LOWER_TAX', '降低税率'), ('BUILD_SCHOOL', '资助村塾'), ('BUILD_IRRIGATION', '修建水利'), ('RELIEF', '赈灾救济'), ('HIRE_BAILIFFS', '增设衙役'), ('RECLAIM_LAND', '开垦荒地'), ('REPAIR_ROADS', '修缮道路'), ('BUILD_GRANARY', '开设义仓'), ('UPGRADE_FACILITY', '升级公共设施'), ('OTHER', '其他')], help_text='承诺类型', max_length=20),
        ),
    ]
