# Generated by Django 4.2.8 on 2026-04-10 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0030_alter_agent_role_alter_negotiationsession_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promise',
            name='direction',
            field=models.CharField(choices=[('PLAYER_TO_NPC', '玩家向NPC承诺'), ('NPC_TO_PLAYER', 'NPC向玩家承诺')], default='PLAYER_TO_NPC', help_text='承诺方向', max_length=15),
        ),
        migrations.AlterField(
            model_name='negotiationsession',
            name='event_type',
            field=models.CharField(choices=[('ANNEXATION', '地主兼并'), ('IRRIGATION', '兴建水利'), ('HIDDEN_LAND', '隐匿土地'), ('VILLAGE_REQ_SCHOOL', '村民请愿·建村塾'), ('VILLAGE_REQ_TAX', '村民请愿·减税'), ('LANDLORD_DEMAND_FACILITY', '地主要求·升级公共设施'), ('GENTRY_RELIEF_OFFER', '地主主动救济·开仓放粮')], max_length=30),
        ),
        migrations.AlterField(
            model_name='promise',
            name='promise_type',
            field=models.CharField(choices=[('LOWER_TAX', '降低税率'), ('BUILD_SCHOOL', '资助村塾'), ('BUILD_IRRIGATION', '修建水利'), ('RELIEF', '赈灾救济'), ('HIRE_BAILIFFS', '增设衙役'), ('RECLAIM_LAND', '开垦荒地'), ('REPAIR_ROADS', '修缮道路'), ('BUILD_GRANARY', '开设义仓'), ('UPGRADE_FACILITY', '升级公共设施'), ('RECOMMEND_TALENT', '举荐人才'), ('DONATE_FUNDS', '捐助资金'), ('PROVIDE_LABOR', '提供劳力'), ('OTHER', '其他')], help_text='承诺类型', max_length=20),
        ),
    ]
