# Generated by Django 4.2.8 on 2026-05-13 12:30

from django.db import migrations, models
import django.db.models.deletion


def migrate_legacy_memory(apps, schema_editor):
    Agent = apps.get_model('game', 'Agent')
    AgentMemory = apps.get_model('game', 'AgentMemory')
    for agent in Agent.objects.all().select_related('game'):
        attrs = agent.attributes or {}
        legacy = attrs.get('memory') or []
        if not legacy:
            continue
        season = getattr(agent.game, 'current_season', 1)
        for text in legacy:
            if not isinstance(text, str) or not text.strip():
                continue
            AgentMemory.objects.create(
                agent=agent,
                text=text.strip(),
                topic='OTHER',
                importance=5,
                season=season,
                source='legacy',
                related_entities={},
            )


def reverse_legacy_memory(apps, schema_editor):
    AgentMemory = apps.get_model('game', 'AgentMemory')
    AgentMemory.objects.filter(source='legacy').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_add_promise_direction_and_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('topic', models.CharField(choices=[('POLICY', '施政'), ('PROMISE', '承诺'), ('DISASTER', '灾害'), ('NEGOTIATION', '交涉'), ('CHAT', '闲谈'), ('OTHER', '其他')], default='OTHER', max_length=20)),
                ('importance', models.SmallIntegerField(default=5)),
                ('season', models.SmallIntegerField()),
                ('source', models.CharField(max_length=40)),
                ('related_entities', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='game.agent')),
            ],
            options={
                'indexes': [models.Index(fields=['agent', '-importance', '-season'], name='game_agentm_agent_i_b0a092_idx'), models.Index(fields=['agent', 'topic'], name='game_agentm_agent_i_aad492_idx')],
            },
        ),
        migrations.RunPython(migrate_legacy_memory, reverse_legacy_memory),
    ]
