# Generated by Django 4.2.8 on 2026-04-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, null=True)),
                ('game_id', models.IntegerField(null=True)),
                ('season', models.IntegerField(null=True)),
                ('call_source', models.CharField(max_length=64)),
                ('provider', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=64)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(null=True)),
                ('success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'llm_call_log',
                'indexes': [models.Index(fields=['game_id', 'season'], name='llm_call_lo_game_id_af5fc2_idx'), models.Index(fields=['user_id', 'created_at'], name='llm_call_lo_user_id_11f4f5_idx')],
            },
        ),
    ]
